services:
    app:
        image: freelance-adm-platform
        ports:
            - "8080:8080"  # Map port 8080 of the container to port 8080 on the host
        environment:
          DB_URL: jdbc:postgresql://postgres:5432/freelance_adm_db
          DB_USER: admin
          DB_PASS: admin
        depends_on:
            - rabbitmq
            - postgres
    rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"  # RabbitMQ default port
        - "15672:15672"  # RabbitMQ management UI
      environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin

    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"  # PostgreSQL default port
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: freelance_adm_db
        volumes:
          - pgdata:/var/lib/postgresql/data  # Persist PostgreSQL data

volumes:
  pgdata: