spring:
    application:
        name: freelance-adm-platform
    config:
        import: optional:file:.env[.properties]
    datasource:
        driverClassName: org.postgresql.Driver
        url: '${DB_URL:jdbc:postgresql://localhost:5432/freelance_adm_db}'
        username: '${DB_USERNAME:admin}'
        password: '${DB_PASSWORD:admin}'
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
springdoc:
    api-docs:
        path: /swagger
    swagger-ui:
        path: /swagger-ui
jwt:
    public:
        key: 'classpath:app.pub'
    private:
        key: 'classpath:app.key'

management:
  endpoints:
      web:
          exposure:
            include: health, metrics, info, env
          base-path: /actuator
